services:
  fast-api:
    environment:
      TZ: Asia/Seoul
    build:
      context: ${CONTEXT_PATH}
      dockerfile: Dockerfile
      args:
        APP_DIR: ${WORK_DIR}
        APP_PORT: ${INTERNAL_PORT}
    ports:
      - ${EXPOSED_PORT}:${INTERNAL_PORT}
    volumes:
      - .:${WORK_DIR}
    networks:
      - custom_network
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 3
    env_file:
      - .env

networks:
  custom_network:
    driver: bridge
    name: ${NETWORK_NAME}
